endpoints:
  cloud-api: https://api.eu1.robocorp.com
  cloud-linking: https://id.robocorp.com
  pypi: # https://pypi.org/simple
  pypi-trusted: # https://pypi.org
  conda: # https://repo.anaconda.org
  downloads: https://downloads.robocorp.com
  docs: https://robocorp.com/docs
  telemetry: https://telemetry.robocorp.com
  issues: https://telemetry.robocorp.com

diagnostics-hosts:
  - files.pythonhosted.org
  - github.com
  - repo.anaconda.org
  - pypi.org

autoupdates:
  assistant: https://downloads.robocorp.com/assistant/releases
  workforce-agent: https://downloads.robocorp.com/workforce-agent/releases
  lab: https://downloads.code.robocorp.com/lab/installer

certificates:
  verify-ssl: true

branding:
  logo: https://downloads.robocorp.com/company/press-kit/logos/robocorp-logo-black.svg
  theme-color: FF0000

meta:
  source: builtin
  version: 2021.03
